---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  firefox: "51.0"

cache:
  yarn: true

env:
  matrix:
  - EMBER_TRY_SCENARIO=ember-1-13
  - EMBER_TRY_SCENARIO=ember-2-4
  - EMBER_TRY_SCENARIO=ember-2-8
  - EMBER_TRY_SCENARIO=ember-2-10
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta

before_install:
  - "curl -o- -L https://yarnpkg.com/install.sh | bash"
  - "export PATH=$HOME/.yarn/bin:$PATH"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - yarn install --no-lockfile

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

deploy:
  provider: npm
  email: admin@ember-redux.com
  skip_cleanup: true
  api_key:
    secure: fjxKe3kznGSPmNQla1oykCGKvuXdMO6UrtCe21toGf0Az5IK4NAtsaweBHjCHmsb88sFaQUmZIWi+J6AR6MpKZb+D/VkUGbjoikrN9UdAkfSfIN2IYMBwpXHjX24sBIzD/IOaSO/hDKj9nfDiR8k85x3V9VTiU7gyKsxOt1JT00UBKi0IS3TAyMXwnqKgNTsYq4BTuUtmx5JzJrSAxV2XU8bI/HFEMe5ygxQ5ZveYca2R0oZFYGMyOqj3iE5fDuthO2O2YKIRd6a/u0nBEmUhYMFhVKF8akqsh0QMToQlCjOBGp6csYIb9Ay6+PsD2n1eTBID3bvutLphYDjjmqHqnfTZCCpGUAh0tPj3NWusEb2UlSkgOcVNzVrk+/OjKzBvTjj4VXT9saTgEaKB/kZMaxkxuzzIQelYR/p/fUgfThizfr+7qVuKFgbKE48t9WMxA3HOqjriWtFe/W66BNv3pBh2DAM/tMAv/4lg2Sheego27MAXOlSQh13CAo5XeXvFUszlJuFFpw161OAyWN2818Kxn2sL2L/2j4E3cVGKiX7VHjplJy94QHz8VIMSTkkKMzVoe04mO6xL5vRqalPxn29ti0RACkofX7WY/nUmAVQBe7FlIfdZ07flFk3HeKuA7sxdi0maLULLfOsACZ/1y578+pvE99amQSudCTootw=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: 'stable'
    tags: true
